#!/bin/sh
#
# Inmarsat BGAN services
#

NAME=IBGAN
PID_FILE=/var/run/$NAME.pid
LOG_DIR=/opt/log/$NAME
DAEMON=/opt/Inmarsat/$NAME

logfile()
{
    suffix=0
    file="$LOG_DIR/$NAME.log"
    if [ -e "$file" ]
    then
        while test -e "$file"; do
            file="$LOG_DIR/$NAME.log.$((++suffix))"
        done
        mv -v $LOG_DIR/$NAME.log "$file"
    fi
}

case "$1" in
    start)
        echo "Starting ${NAME}: "
        mkdir -p $LOG_DIR
        logfile
        start-stop-daemon -S -q -m -b -p ${PID_FILE} -C -x  $DAEMON > $LOG_DIR/$NAME.log 2>&1
        rc=$?
        if [ $rc -eq 0 ]
        then
            echo "OK"
        else
            echo "FAIL" >&2
        fi
        ;;
    stop)
        echo "Stopping ${NAME}: "
        start-stop-daemon -K -q -p ${PID_FILE}
        rc=$?
        if [ $rc -eq 0 ]
        then
            echo "OK"
        else
            echo "FAIL" >&2
        fi
        ;;
    restart)
        "$0" stop
        "$0" start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        ;;
esac


exit $?
