#!/bin/sh
#
# start portal services
#

NAME=lora-app-server

certificateHandling() {
	echo "Certificate handler: "
	if [[ ! -r /etc/$NAME/certs/http-key.pem ]] && [[ ! -r /etc/$NAME/certs/http.pem ]]; then
		mkdir -p /etc/$NAME/certs
		openssl req -x509 -newkey rsa:4096 -keyout /etc/$NAME/certs/http-key.pem -out /etc/$NAME/certs/http.pem -days 365 -nodes -batch -subj "/CN=localhost"
		echo "A self-signed TLS certificate has been generated : /etc/$NAME/certs"
	fi
}

startDatabase() {
	echo "Starting Postgres Database: "
	OUTPUT="$(sudo -u postgres psql -c "\du")"
	reqsub='loraserver_as'
	if [ -z "${OUTPUT##*$reqsub*}" ] ;then
		echo "Role Exists: '$reqsub'."
	else
		echo "Role doesn't Exists: '$reqsub'. Adding ..."
		sudo -u postgres psql -c "create role loraserver_as with login password 'dbpassword';"
	fi
	reqsub='loraserver_ns'
	if [ -z "${OUTPUT##*$reqsub*}" ] ;then
		echo "Role Exists: '$reqsub'."
	else
		echo "Role doesn't Exists: '$reqsub'. Adding ..."
		sudo -u postgres psql -c "create role loraserver_ns with login password 'dbpassword';"
	fi

	OUTPUT="$(sudo -u postgres psql -c "\l")"
	reqsub='loraserver_as'
	if [ -z "${OUTPUT##*$reqsub*}" ] ;then
		echo "Database Exists: '$reqsub'."
	else
		echo "Database doesn't Exists: '$reqsub'. Adding ..."
		sudo -u postgres psql -c "create database loraserver_as with owner loraserver_as;"
	fi
	reqsub='loraserver_ns'
	if [ -z "${OUTPUT##*$reqsub*}" ] ;then
		echo "Database Exists: '$reqsub'."
	else
		echo "Database doesn't Exists: '$reqsub'. Adding ..."
		sudo -u postgres psql -c "create database loraserver_ns with owner loraserver_ns;"
	fi

	echo "Database Setup Done"
}
start() {
	echo "Starting Portal Services: "
	startDatabase
	echo "Certificates: "
	certificateHandling
	echo "Portal services: "
	mkdir -p /var/log/lora_gateway
	mkdir -p /var/log/lora_pkt_fwd
	/usr/bin/lora_gateway/reset_lgw.sh start 17
	/usr/bin/lora_gateway/libloragw/test_loragw_reg > /var/log/lora_gateway/lora_gateway
	start-stop-daemon -S -q -m -b -p /var/run/lora_pkt_fwd.pid -C -x  /usr/bin/packet_forwarder/lora_pkt_fwd/lora_pkt_fwd > /var/log/lora_pkt_fwd/lora_pkt_fwd.log 2>&1
	/usr/sbin/loraServer/loraServerInit lora-gateway-bridge start
	/usr/sbin/loraServer/loraServerInit loraserver start
	/usr/sbin/loraServer/loraServerInit lora-app-server start
	echo "Started Portal Services"
}
stop() {
	echo "Stopping Portal Services: "
	start-stop-daemon -K -q -p /var/run/lora_pkt_fwd.pid
	/usr/sbin/loraServer/loraServerInit lora-gateway-bridge stop
	/usr/sbin/loraServer/loraServerInit loraserver stop
	/usr/sbin/loraServer/loraServerInit lora-app-server stop
	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart|reload)
		restart
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac

exit $?
